// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uipxbxracugvfnhxtsaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcHhieHJhY3VndmZuaHh0c2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzA4NTgsImV4cCI6MjA3MTU0Njg1OH0.T6WJn-qZzrosHBYEaI__8w1_S9sYJZZo7-xDKcvtNRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});